project:
  type: website

website:
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    title: Welcome
    tools:
      - icon: house-fill
        href: https://isss608-ohjiawen.netlify.app/
      - icon: github
        href: https://github.com/jiawenoh/ISSS608-VAA
      - icon: linkedin
        href: https://www.linkedin.com/in/jia-wen-oh/
        
    background: light
    reader-mode: true
    collapse-level: 1
    contents:
      - section: "About"
        contents: 
          - text: "Home"
            href: "index.qmd"
          - text: "About Me"
            href: "about_me.qmd"
         
      - section: "Hands-on Exercise"
        contents:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"

      - section: "In-class Exercise"
        contents:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
            
      - section: "Take Home Exercise"
        contents:
          - text: "Take Home Exercise 1"
            href: "Take-Home_Ex/Take_Home_Ex01/Take-Home_Ex01.html"
          - text: "Take Home Exercise 2"
            href: "Take-Home_Ex/Take_Home_Ex02/Take-Home_Ex02.html"
            
format:
  html:
    theme:
      light: flatly
      dark: [flatly, theme-dark.scss]
    css: styles.css
    code-fold: false
    code-summary: "Show the code"
    toc: true
    
editor: visual
