project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    title: Welcome
    tools:
      - icon: github
        href: https://github.com/jiawenoh/ISSS608-VAA
      - icon: linkedin
        href: https://www.linkedin.com/in/jia-wen-oh/
    background: dark
    reader-mode: true
    collapse-level: 1
    contents:
      - section: "About"
        contents: 
          - text: "Home"
            href: "index.qmd"
          - text: "About Me"
            href: "about_me.qmd"
         
      - section: "Hands-on Exercise"
        contents:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"

      - section: "In-class Exercise"
        contents:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
            
format:
  html:
    theme: 
      dark: flatly
    css: styles.css
    code-fold: show
    code-summary: "Hide the code"
    toc: true

     
editor: visual
