---
title: "Take Home Exercise 3"
subtitle: " Mini Case 3 of Vast Challenge 2023"
author: "Oh Jia Wen"
date: "6/4/2023"
date-modified: "6/4/2023"
execute: 
  echo: true
  eval: true
  warning: false
---

# 1. OVERVIEW

## 1.1 The Task

# 2. Datasets

# 3. Data Preparation

## 3.1 Install R-packages

Using p_load() of pacman package to load and install the following libraries:

```{r}
pacman::p_load(jsonlite, tidygraph, ggraph,visNetwork, graphlayouts,
               ggforce, tidytext, tidyverse)
```

## 3.2 Importing Data

Importing JSON file by using jsonlite package.

```{r}
MC3_challenge <- fromJSON("data/MC3.json")
```

This is not a directed graph. There is no flow by degree (directed = FALSE)

```{r}
MC3_edges <-as_tibble(MC3_challenge$links) %>%
  distinct() %>%
  mutate(source = as.character(source),
         target = as.character(target),
         type = as.character(type)) %>%
  group_by(source,target, type) %>%
  summarise(weights = n()) %>%
  filter (source != target) %>%
  ungroup()
```

```{r}
MC3_nodes <-as_tibble(MC3_challenge$nodes) %>%
  mutate(country = as.character(country),
         id = as.character(id),
         product_services = as.character(product_services),
         revenue_omu = as.numeric(as.character(revenue_omu)),
         type = as.character(type)) %>%
  select(id,country,type,revenue_omu,product_services)
```
